### ISSUE TITLE
Hosting and working

### ISSUE THREAD

**Issue by NV4s** [kgurchiek/n-gon-multiplayer#2]
How do I set this up with n-gon (they disabled javascript/bookmarklets). Also, can you give me a step-by-step or video tutorial on how to host this?

**Comment by kgurchiek** [comment]
Is https://cornbread2100.com blocked by your school?

**Comment by NV4s** [comment]
YEs

**Comment by kgurchiek** [comment]
Then go on replit, create a new Node.js project, and run `require('https').createServer((req, res) => res.end('test')).listen(80)` and it'll pop up a window on the right that contains the repl's url. Then run the server script on the repl and replace the websocket url on the client scripts with the repl url.

**Comment by NV4s** [comment]
Didn't work

**Comment by creator1116** [comment]
where else can it be hosted? vercel does not work

**Comment by MythicalTrashcan** [comment]
Could work with a self hosting tutorial.

**Comment by kgurchiek** [comment]
I'll do that once it's actually finished and working

**Comment by MythicalTrashcan** [comment]
Is it not currently working?

**Comment by kgurchiek** [comment]
it's currently maybe a third of the way done, the only thing functioning is the race branch

**Comment by MythicalTrashcan** [comment]
So what does this currently do now?

**Comment by kgurchiek** [comment]
The race branch just lets you see what the other player is doing, but you don't interact with each other at all. The main branch will be a full co-op when it's done, but right now there's only block and powerup syncing. Some guns also work, but I'm currently working on mobs.

**Comment by MythicalTrashcan** [comment]
I haven't hosted this yet. How does a client even connect?

**Comment by MythicalTrashcan** [comment]
And this join script will be a js bookmarklet right? If so, the main issue is some friends at my school have js bookmarklets disabled by policy. I do have a running copy of n-gon with a prompt to enable your control scripts for mobile and controller. I could always add in that bookmarklet into the js if needed,

**Comment by kgurchiek** [comment]
Yeah this is a js script to inject into n-gon, so you could run that with a bookmarklet or dev console. I'll also add it to my website once it's finished, so if those are disabled you could use the website instead.

**Comment by kgurchiek** [comment]
@4kh00 the main co-op mode isn't finished yet, but you can play the race branch, which just lets you see the other player and their fields while playing the game

**Comment by kgurchiek** [comment]
On the race branch there's no actual interaction between the two players, you just see what they're doing. In the main co-op mode everything will be synced so you can work together.

`http.js` is a simple Node.js http server for locally hosting the scripts locally. `generateMobIds.js` was a script I used to write all the mob spawn wrappers for me so I didn't have to do so much manual copying. It takes `mobs.js` as input (which is just copied from n-gon) and outputs to `mobIdWrappers.js`.
